name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: cd ./src && dotnet restore
    - name: Build
      run: cd ./src && dotnet build --configuration Release --no-restore
    - name: Test
      run: cd ./src && dotnet test --no-restore --verbosity normal
    - name: Pack with dotnet
      run: cd ./src && dotnet pack ./GitHubActions.Models/GitHubActions.Models.csproj --output nuget-packages --configuration Release
    - name: Push with dotnet
      run: cd ./src && dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

